//file:noinspection GroovyAssignabilityCheck
//file:noinspection GrUnresolvedAccess
apply plugin: 'com.android.application'
apply plugin: 'dagger.hilt.android.plugin'
// Google Services plugin (required for firebase)
apply plugin: 'com.google.gms.google-services'
// firebase plugins
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.google.firebase.appdistribution'

// for Codemagic CI/CD
def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    //noinspection GrUnresolvedAccess
    compileSdkVersion libs.versions.compileSdk.get().toInteger()
    defaultConfig {
        applicationId "com.music.android.sensilence"
        minSdkVersion rootProject.min_sdk_version
        targetSdkVersion rootProject.target_sdk_version
        versionCode rootProject.version_code
        versionName rootProject.version_name

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        buildConfigField "String", "DATABASE_SONGS", "\"rootProject.DATABASE_SONGS\""

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.schemaLocation"  : "$projectDir/schemas".toString(),
                        "room.incremental"     : "true",
                        "room.expandProjection": "true"
                ]
            }
        }
//        Remove unused alternative resources
//        (https://developer.android.com/studio/build/shrink-code#unused-alt-resources)
         resourceConfigurations += ['en', 'ua']
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    signingConfigs {
        production {
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
        }
        dev {
            storeFile file(rootProject.SIGNING_KEY_DEBUG_PATH)
            storePassword rootProject.SIGNING_KEY_DEBUG_PASSWORD
            keyAlias rootProject.SIGNING_KEY_DEBUG_KEY
            keyPassword rootProject.SIGNING_KEY_DEBUG_KEY_PASSWORD
        }
    }

    buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // project's release build type.
            // https://developer.android.com/studio/build/shrink-code#enable
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    // List additional ProGuard rules for the given build type here. By default,
                    // Android Studio creates and includes an empty rules file (located
                    // at the root directory of each module).
                    'proguard-rules.pro'
            signingConfig signingConfigs.production
        }
        debug {
            signingConfig signingConfigs.dev
            pseudoLocalesEnabled true
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
    namespace 'com.music.android.sensilence'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':domain')
    implementation project(':data')

    implementation libs.appcompat
    implementation libs.material
    implementation libs.viewpager2

    /* Allowing app to build and read multiple DEX files.
     * Avoids an error that indicates that the app has reached
     * the limit of the Android build architecture. */
    implementation libs.multidex

    // required app module hilt dependency
    implementation libs.hilt.android

    implementation libs.annotations

    /* Firebase Bill of Materials.
     * By using the Firebase Android BoM,
     * app will always use compatible versions of the Firebase Android libraries. */
    implementation libs.firebase.bom

    // Firebase SDK for Google Analytics
    implementation(libs.firebase.analytics) {
        // remove advertising dependency
        exclude module: "play-services-ads-identifier"
        exclude module: "play-services-measurement"
        exclude module: "play-services-measurement-sdk"
    }
    implementation libs.firebase.crashlytics
    implementation libs.firebase.perf
    // Firebase Cloud Messaging
    implementation libs.firebase.messaging

    // added to avoid errors with libraries, which using kotlin
    //noinspection DifferentStdlibGradleVersion
    implementation libs.kotlin.stdlib.jdk8

    // database (Room)
    implementation libs.room.runtime
    annotationProcessor libs.room.compiler

    // test
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    androidTestImplementation libs.runner
    androidTestImplementation libs.core
}

repositories {
    google()
    mavenCentral()
}