//file:noinspection GroovyAssignabilityCheck
//file:noinspection GrUnresolvedAccess
plugins {
    id 'com.android.library'
}

android {
    compileSdkVersion rootProject.compile_sdk_version

    defaultConfig {
        minSdkVersion rootProject.min_sdk_version

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.schemaLocation"  : "$projectDir/schemas".toString(),
                        "room.incremental"     : "true",
                        "room.expandProjection": "true"
                ]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'io.github.turskyi.data'
    testOptions {
        targetSdk 37
    }
    lint {
        targetSdk 37
    }
}

dependencies {
    implementation project(':domain')

    implementation libs.appcompat
    implementation libs.material

    // database (Room)
    implementation libs.room.runtime
    annotationProcessor libs.room.compiler
    implementation libs.room.rxjava2

    // test
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}

repositories {
    google()
    mavenCentral()
}